language: php

php:
  - 5.6
  - 7.0

install:
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/coveralls
